### ISSUE TITLE
Version 6 Beta doesn't work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jkoo7yeha/dompdf#157]
```
What steps will reproduce the problem?
1. HTML pure or
2. Instruccion $pdf->


What is the expected output? What do you see instead?
A PDF as a result.
The following error in both cases.
Fatal error: Uncaught exception 'DOMPDF_Exception' with message 'No block-level 
parent found. Not good.' in 
C:\WebSite\Mensajeria\dompdf\include\inline_positioner.cls.php:68 Stack trace: 
#0 C:\WebSite\Mensajeria\dompdf\include\frame_decorator.cls.php(382): 
Inline_Positioner->position() #1 
C:\WebSite\Mensajeria\dompdf\include\inline_frame_reflower.cls.php(56): 
Frame_Decorator->position() #2 
C:\WebSite\Mensajeria\dompdf\include\frame_decorator.cls.php(388): 
Inline_Frame_Reflower->reflow() #3 
C:\WebSite\Mensajeria\dompdf\include\page_frame_reflower.cls.php(96): 
Frame_Decorator->reflow() #4 
C:\WebSite\Mensajeria\dompdf\include\frame_decorator.cls.php(388): 
Page_Frame_Reflower->reflow() #5 
C:\WebSite\Mensajeria\dompdf\include\dompdf.cls.php(525): 
Frame_Decorator->reflow() #6 C:\WebSite\Mensajeria\PROEstIVACompras.php(800): 
DOMPDF->render() #7 {main} thrown in 
C:\WebSite\Mensajeria\dompdf\include\inline_positioner.cls.php  on line 68


What version of the product are you using? On what operating system?
6 Beta
XP, Apache 2.2.13, php 5.2.11


Please provide any additional information below.
This source work with the version 5.1 except for many pages.


```

Original issue reported on code.google.com by `farozenb...@gmail.com` on 27 Jun 2010 at 4:41

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Also, can you check your PHP error log for any warnings/notices. I seem to 
recall that there might have been an issue with a missing function that could 
cause this error when the mbstring extension was not enabled.
```

Original comment by `eclecticgeek` on 28 Aug 2010 at 2:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `fabien.menager` on 10 Apr 2011 at 7:19
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
Original comment by `eclecticgeek` on 30 May 2013 at 5:15
- Added labels: **Restrict-AddIssueComment-Commit**
