### ISSUE TITLE
When i am trying runtime PDF generation then got following error.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jkoo7yeha/dompdf#393]
```
Uncaught exception 'DOMPDF_Exception' with message 'Unknown image type: .' in 
/home/content/58/5427858/html/itinerary-admin/include/image_cache.cls.php:81 
Stack trace: 
#0 
/home/content/58/5427858/html/itinerary-admin/include/image_frame_decorator.cls.
php(88): Image_Cache::resolve_url('', NULL, '', '') 
#1 
/home/content/58/5427858/html/itinerary-admin/include/frame_factory.cls.php(169)
: Image_Frame_Decorator->__construct(Object(Frame), Object(DOMPDF)) 
#2 /home/content/58/5427858/html/itinerary-admin/include/dompdf.cls.php(392): 
Frame_Factory::decorate_frame(Object(Frame), Object(DOMPDF)) 
#3 /home/content/58/5427858/html/itinerary-admin/manage_itinerary.php(294): 
DOMPDF->render() 
#4 /home/content/58/5427858/html/itinerary-admin/adminmain.php(135): 
include('/home/content/5...') 
#5 /home/content/58/5427858/html/itinerary-admin/index1.php(111): 
include('/home/content/5...') 
#6 {main} thrown in 
/home/content/58/5427858/html/itinerary-admin/include/image_cache.cls.php  on 
line 81
```

Original issue reported on code.google.com by `rakeshghij` on 16 Dec 2011 at 5:21

Attachments:
- [error.jpg](https://storage.googleapis.com/google-code-attachments/dompdf/issue-393/comment-0/error.jpg)

**Comment by GoogleCodeExporter** [comment]
```
Which version of dompdf? Looks like 0.5.1. We recommend upgrading to the latest 
version (currently 0.6.0 beta 2) if possible.

There's something about your URL that dompdf doesn't like. It would help to see 
a sample document that generates the error.

FYI, the pop-up you attached a sample of is just indicative that the error 
message was caught in the output buffer and sent as part of the PDF.
```

Original comment by `eclecticgeek` on 17 Dec 2011 at 1:37

**Comment by GoogleCodeExporter** [comment]
Original comment by `eclecticgeek` on 24 May 2013 at 3:00
- Added labels: **Restrict-AddIssueComment-Commit**
