### ISSUE TITLE
Exception when rendering lists within table cell

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jkoo7yeha/dompdf#45]
```
What steps will reproduce the problem?
1. Add <table> <tr> <td> <ul> <li> this is a test </li> </ul> </td> </tr>
</table>   
2. Attempt to render PDF
3. Throws exception 

What is the expected output? What do you see instead?
Bullet list rendered inside a table

What version of the product are you using? On what operating system?
Latest version as of 7/29/09

Please provide any additional information below.
Is it possible to render this without the order list via a simple patch?
```

Original issue reported on code.google.com by `utahs...@gmail.com` on 29 Jul 2009 at 9:42

**Comment by GoogleCodeExporter** [comment]
```
exception 'DOMPDF_Internal_Exception' with message 'Frame not found in cellmap' 
in
/home/www/wiki/extensions/PdfExport/dompdf/include/cellmap.cls.php:239
Stack trace:

#0
/home/www/wiki/extensions/PdfExport/dompdf/include/table_cell_frame_reflower.cls
.php(66):
Cellmap->get_frame_position(Object(Table_Cell_Frame_Decorator))
#1 
/home/www/wiki/extensions/PdfExport/dompdf/include/frame_decorator.cls.php(387):
Table_Cell_Frame_Reflower->reflow()
#2
/home/www/wiki/extensions/PdfExport/dompdf/include/table_row_frame_reflower.cls.
php(70):
Frame_Decorator->reflow()
#3 
/home/www/wiki/extensions/PdfExport/dompdf/include/frame_decorator.cls.php(387):
Table_Row_Frame_Reflower->reflow()
#4
/home/www/wiki/extensions/PdfExport/dompdf/include/table_frame_reflower.cls.php(
468):
Frame_Decorator->reflow()
#5 
/home/www/wiki/extensions/PdfExport/dompdf/include/frame_decorator.cls.php(387):
Table_Frame_Reflower->reflow()
#6
/home/www/wiki/extensions/PdfExport/dompdf/include/block_frame_reflower.cls.php(
408):
Frame_Decorator->reflow()
#7 
/home/www/wiki/extensions/PdfExport/dompdf/include/frame_decorator.cls.php(387):
Block_Frame_Reflower->reflow()
#8
/home/www/wiki/extensions/PdfExport/dompdf/include/page_frame_reflower.cls.php(7
8):
Frame_Decorator->reflow()
#9 
/home/www/wiki/extensions/PdfExport/dompdf/include/frame_decorator.cls.php(387):
Page_Frame_Reflower->reflow()
#10 /home/www/wiki/extensions/PdfExport/dompdf/include/dompdf.cls.php(417):
Frame_Decorator->reflow()
#11 /home/www/wiki/extensions/PdfExport/PdfExport_body.php(136): 
DOMPDF->render()
#12 /home/www/wiki/extensions/PdfExport/PdfExport_body.php(171):
SpecialPdf->outputpdf(Array, ' --landscape --...', 'Letter')
#13 /home/www/wiki/includes/SpecialPage.php(534): SpecialPdf->execute(NULL)
#14 /home/www/wiki/includes/Wiki.php(224): 
SpecialPage::executePath(Object(Title))
#15 /home/www/wiki/includes/Wiki.php(55):
MediaWiki->initializeSpecialCases(Object(Title), Object(OutputPage), 
Object(WebRequest))
#16 /home/www/wiki/index.php(93): MediaWiki->initialize(Object(Title), NULL,
Object(OutputPage), Object(User), Object(WebRequest))
#17 /home/www/wiki/index.php5(1): require('/home/www/wiki/...')
#18 {main}

```

Original comment by `utahs...@gmail.com` on 29 Jul 2009 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
I'm not entirely sure that the list element is the main culprit in your 
situation. Cellmap errors tend to show up when tables span 
more than one page. Is the exception you included a result of the code from 
step one or due to a more complex page?

That being said, your test code does indeed cause a crash, though it's not 
consistent. A simple reformatting of the code seems to 
fix the problem. I added line breaks between the tags and that was sufficient.

Either way, the code that causes a crash in 0.5.1 appears to run correctly in 
the trunk.
```

Original comment by `eclecticgeek` on 31 Jul 2009 at 3:30
- Changed state: **Addressed**
- Added labels: **Milestone-Release0.6**

**Comment by GoogleCodeExporter** [comment]
Original comment by `eclecticgeek` on 30 May 2013 at 5:15
- Added labels: **Restrict-AddIssueComment-Commit**
